<h3>Question (ID-95642):</h3><h2>Does an application-wide exception handler make sense?</h2><p>Long story short, I have a substantial Python application that, among other things, does outcalls to "losetup", "mount", etc. on Linux.  Essentially consuming system resources that must be released when complete.</p>

<p>If my application crashes, I want to ensure these system resources are properly released.</p>

<p>Does it make sense to do something like the following?</p>

<pre><code>def main():
    # TODO: main application entry point
    pass

def cleanup():
    # TODO: release system resources here
    pass

if __name__ == "__main__":
    try:
        main()
    except:
        cleanup()
        raise
</code></pre>

<p>Is this something that is typically done?  Is there a better way?  Perhaps the destructor in a singleton class?</p>
<br /><h3>Answers (Total-6):</h3><b>#0</b><br /><p>I like top-level exception handlers in general (regardless of language). They're a great place to cleanup resources that may not be immediately related to resources consumed inside the method that throws the exception.</p>

<p>It's also a fantastic place to <strong>log</strong> those exceptions if you have such a framework in place. Top-level handlers will catch those bizarre exceptions you didn't plan on and let you correct them in the future, otherwise, you may never know about them at all.</p>

<p>Just be careful that your top-level handler doesn't throw exceptions!</p>
<br /><b>#1</b><br /><p>A destructor (as in a __del__ method) is a bad idea, as these are not guaranteed to be called. The atexit module is a safer approach, although these will still not fire if the Python interpreter crashes (rather than the Python application), or if os._exit() is used, or the process is killed aggressively, or the machine reboots. (Of course, the last item isn't an issue in your case.) If your process is crash-prone (it uses fickle third-party extension modules, for instance) you may want to do the cleanup in a simple parent process for more isolation.</p>

<p>If you aren't really worried, use the atexit module.</p>
<br /><b>#2</b><br /><p>Application wide handler is fine. They are great for logging. Just make sure that the application wide one is durable and is unlikely to crash itself.</p>
<br /><b>#3</b><br /><p>if you use classes, you should free the resources they allocate in their destructors instead, of course. Use the try: on entire application just if you want to free resources that aren't already liberated by your classes' destructors.</p>

<p>And instead of using a catch-all except:, you should use the following block:</p>

<pre><code>try:
    main()
finally:
    cleanup()
</code></pre>

<p>That will ensure cleanup in a more pythonic way.</p>
<br /><b>#4</b><br /><p>That seems like a reasonable approach, and more straightforward and reliable than a destructor on a singleton class.  You might also look at the "<a href="http://docs.python.org/lib/module-atexit.html" rel="nofollow">atexit</a>" module.  (Pronounced "at exit", not "a tex it" or something like that.  I confused that for a long while.)</p>
<br /><b>#5</b><br /><p>Consider writing a context manager and using the with statement.</p>
<br />