<h3>Question (ID-6182693):</h3><h2>Python -- Send Email When Exception Is Raised?</h2><p>I have a <code>python</code> class with many methods():</p>

<p><code>Method1()</code></p>

<p><code>Method2()</code></p>

<p>...........</p>

<p>...........</p>

<p><code>MethodN()</code></p>

<p>All methods -- while performing different tasks -- have the same scheme:</p>

<pre><code>do something
do something else
has anything gone wrong?
    raise an exception
</code></pre>

<hr>

<p>I want to be able to get an email whenever an exception is raised anywhere in the class.</p>

<p>Is there some easy way to combine this logic into the class, rather than calling <code>SendEmail()</code> before every <code>raise Exception</code> statement? what is the right, pythonic way to deal with such a case? canh a 'generalized' Exception handler be the solution? I'd be glad for any ideas you may have.</p>
<br /><h3>Answers (Total-8):</h3><b>#0</b><br /><p>Something like this, perhaps?</p>

<pre><code>def mailexception(ex):
  # Be creative.
  print 'Mailing... NOW!'

def pokemontrainer(cls):
  class Rye(cls):
    def __getattribute__(self, name):
      def catcher(func):
        def caller(*args, **kwargs):
          try:
            func(*args, **kwargs)
          except Exception, e:
            mailexception(e)
            raise
        return caller
      ref = cls.__getattribute__(self, name)
      if hasattr(cls, name) and hasattr(getattr(cls, name), '__call__'):
        return catcher(ref)
  return Rye

@pokemontrainer
class Exceptor(object):
  def toss(self, e):
    raise e('Incoming salad!')

ex = Exceptor()
ex.toss(ValueError)
</code></pre>
<br /><b>#1</b><br /><p>Beware <a href="http://www.youtube.com/watch?v=XChxLGnIwCU" rel="nofollow">the wizard's apprentice</a>!</p>

<p>It would be better to log those errors, then check to see when the last email was sent, and if the timespan is too short, do not send another message because the human being will already be looking at the log file. For many things, one message per day would be enough, but even for system critical things, if you have already had one failure, what could go wrong if you wait two hours to send the next email?</p>

<p>If you send one email per two hour timespan, then the maximum number of emails per day is 12. And if you get a cascading failure (you will!) then it will most likely happen within a couple of hours of the first failure event.</p>

<p>Most large networking companies offer an SLA of 4 hour to fix a failure, measured from the time it first occurs (because cascading failures tend to repeat) until the customer is satisified that it is fixed. If you have a tighter SLA than that, then unless it is some finance industry service, you probably are offering too high of a service level.</p>

<p>But if you do have a 4 hour SLA, then I would make sure that any email sent within 2 - 4 hours of the last email, should use whatever bells and whistles you can to prioritise it, highlight it, etc. For instance use the X-Priority header and put the word URGENT in the subject so that your mail client can display it in large bold red letters.</p>
<br /><b>#2</b><br /><p>Python stdlib has dedicated class to do what you want. See <code>logging.handlers.SMTPHandler</code></p>
<br /><b>#3</b><br /><p>How about this:</p>

<pre><code>class MyException(Exception):
    def __init__(self):
        SendEmail()
</code></pre>
<br /><b>#4</b><br /><p>I'd just <a href="http://docs.python.org/tutorial/errors.html#user-defined-exceptions" rel="nofollow">subclass <code>Exception</code></a> and send the e-mail in the custom Exception. </p>
<br /><b>#5</b><br /><p>Hold on a second. I reread your question, and suddenly feel that the answer to this problem is very simple. If the alternative is this:</p>

<pre><code>if problem_test():
    SendEmail()
    raise Exception
</code></pre>

<p>Then why don't you just define a custom <code>raise_email</code> method?</p>

<pre><code>def raise_email(self, e):
    SendEmail()
    raise e
</code></pre>
<br /><b>#6</b><br /><p>You can use an except hook to send an email when an exception is not caught.</p>

<p>see <a href="http://www.python.org/doc//current/library/sys.html#sys.excepthook" rel="nofollow">sys.excepthook</a></p>
<br /><b>#7</b><br /><p>Guys, like @User said before Python has logging.handlers.SMTPHandle to send logged error message. Use logging module! Overriding exception class to send an email is a bad idea.</p>

<p>Quick example:</p>

<pre><code>import logging
import logging.handlers

smtp_handler = logging.handlers.SMTPHandler(mailhost=("smtp.example.com", 25),
                                            fromaddr="from@example.com", 
                                            toaddrs="to@example.com",
                                            subject=u"AppName error!")


logger = logging.getLogger()
logger.addHandler(smtp_handler)

try:
  break
except Exception as e:
  logger.error(e)
</code></pre>

<p>Regards.</p>
<br />