<h3>Question ( ID-1591319 ) : </h3><h2>Python : How can I know which exceptions might be thrown <span style="background-color:yellow;">from</span> a method call </h2><p>Is there a way knowing ( at coding time ) which exceptions to expect when executing python code ? I end up catching the base Exception class 90 % of the time since I do <span style="background-color:yellow;">n't</span> know which exception type might be thrown ( and do <span style="background-color:yellow;">n't</span> tell me to read the documentation. many times an exception can be propagated <span style="background-color:yellow;">from</span> the deep. and many times the documentation is <span style="background-color:yellow;">not</span> updated or correct ) . Is there some kind of tool to check this ? ( like by reading the python code and libs ) ? </p>
<br /><h3>Answers ( Total-6 ) : </h3><b># 0 </b><br /><p>You should only catch exceptions that you will handle . </p>
<p>Catching all exceptions by their concrete types is <span style="background-color:yellow;">nonsense.</span> You should catch specific exceptions you can and will handle. For other exceptions , you may write a generic catch that catches " base Exception " , logs it ( use str ( ) <span style="background-color:yellow;">function</span> ) and terminates your program ( or does something else that 's appropriate in a crashy situation ) . </p>
<p>If you really gon <span style="background-color:yellow;">na</span> handle all exceptions and are sure <span style="background-color:yellow;">none</span> of them are <span style="background-color:yellow;">fatal</span> ( <span style="background-color:yellow;">for</span> example , if you 're running the code in some kind of a sandboxed environment ) , then your approach of catching generic BaseException <span style="background-color:yellow;">fits</span> your aims . </p>
<p>You might be also interested in language exception reference , <span style="background-color:yellow;">not</span> a reference <span style="background-color:yellow;">for</span> the library you 're using . </p>
<p>If the library reference is really poor and it does <span style="background-color:yellow;">n't</span> re-throw its own exceptions when catching system ones , the only useful approach is to run tests ( maybe add it to test suite , because if something is undocumented , it may change ! ) . Delete a <span style="background-color:yellow;">file</span> crucial <span style="background-color:yellow;">for</span> your code and check what exception is being thrown. Supply too much data and check what error it yields . </p>
<p>You will have to run tests anyway , since , even if the method of getting the exceptions by source code existed , it would <span style="background-color:yellow;">n't</span> give you any idea how you should handle any of those . Maybe you should be showing error message " File <span style="background-color:yellow;">needful.txt</span> is <span style="background-color:yellow;">not</span> <span style="background-color:yellow;">found</span> ! " when you catch IndexError ? Only test can tell . </p>
<br /><b># 1 </b><br /><p>I guess a solution could be only imprecise because of lack of static typing rules . </p>
<p>I 'm <span style="background-color:yellow;">not</span> aware of some tool that checks exceptions , but you could come up with your own tool matching your <span style="background-color:yellow;">needs</span> ( a good chance to play a little with static analysis ) . </p>
<p>As a <span style="background-color:yellow;">first</span> attempt , you could write a <span style="background-color:yellow;">function</span> that builds an AST , <span style="background-color:yellow;">finds</span> all Raise <span style="background-color:yellow;">nodes</span> , and then tries to <span style="background-color:yellow;">figure</span> out common patterns of raising exceptions ( e. g. calling a constructor directly ) </p>
<p>Let <span style="background-color:yellow;">x</span> be the <span style="background-color:yellow;">following</span> program : </p>
<pre><code>x = '''\
if f(x):
    raise IOError(errno.ENOENT, 'not found')
else:
    e = g(x)
    raise e
'''
</code></pre>
<p>Build the AST using the <span style="background-color:yellow;">compiler</span> package : </p>
<pre><code>tree = compiler.parse(x)
</code></pre>
<p>Then define a Raise visitor class : </p>
<pre><code>class RaiseVisitor(object):
    def __init__(self):
        self.nodes = []
    def visitRaise(self, n):
        self.nodes.append(n)
</code></pre>
<p>And <span style="background-color:yellow;">walk</span> the AST collecting Raise <span style="background-color:yellow;">nodes</span> : </p>
<pre><code>v = RaiseVisitor()
compiler.walk(tree, v)

>>> print v.nodes
[
    Raise(
        CallFunc(
            Name('IOError'),
            [Getattr(Name('errno'), 'ENOENT'), Const('not found')],
            None, None),
        None, None),
    Raise(Name('e'), None, None),
]
</code></pre>
<p>You may continue by resolving symbols using <span style="background-color:yellow;">compiler</span> symbol tables , analyzing data dependencies , etc. Or you may just deduce , that CallFunc ( Name ( 'IOError ' ) , ... ) " should definitely mean raising IOError " , which is quite OK <span style="background-color:yellow;">for</span> quick practical results : ) </p>
<br /><b># 2 </b><br /><p>The correct tool to solve this problem is unittests. If you are having exceptions raised by real code that the unittests do <span style="background-color:yellow;">not</span> raise , then you <span style="background-color:yellow;">need</span> more unittests . </p>
<p>Consider this </p>
<pre><code>def f(duck):
    try:
        duck.quack()
    except ??? could be anything
</code></pre>
<p><span style="background-color:yellow;">duck</span> can be any <span style="background-color:yellow;">object</span> </p>
<p>Obviously you can have an AttributeError if <span style="background-color:yellow;">duck</span> has <span style="background-color:yellow;">no</span> quack , a TypeError if <span style="background-color:yellow;">duck</span> has a quack but it is <span style="background-color:yellow;">not</span> callable. You have <span style="background-color:yellow;">no</span> idea what <span style="background-color:yellow;">duck.quack</span> ( ) might raise though , maybe even a DuckError or something </p>
<p>Now supposing you have code like this </p>
<pre><code>arr[i]=get_something_from_database()
</code></pre>
<p>If it raises an IndexError you do <span style="background-color:yellow;">n't</span> know whether it has come <span style="background-color:yellow;">from</span> arr [ i ] or <span style="background-color:yellow;">from</span> deep inside the database <span style="background-color:yellow;">function.</span> usually it does <span style="background-color:yellow;">n't</span> matter so much where the exception occurred , rather that something went wrong and what you wanted to happen did <span style="background-color:yellow;">n't</span> happen . </p>
<p>A handy technique is to catch and maybe reraise the exception like this </p>
<pre><code>except Exception, e
    #inspect e, decide what to do
    raise
</code></pre>
<br /><b># 3 </b><br /><p>I ran into this when using socket , I wanted to <span style="background-color:yellow;">find</span> out all the error conditions I would run in to ( so rather than trying to create errors and <span style="background-color:yellow;">figure</span> out what socket does I just wanted a concise list ) . Ultimately I ended up grep'ing " /usr/lib64/python2.4/test/test_socket.py " <span style="background-color:yellow;">for</span> " raise " : </p>
<pre><code>$ grep raise test_socket.py
Any exceptions raised by the clients during their tests
        raise TypeError, "test_func must be a callable function"
    raise NotImplementedError, "clientSetUp must be implemented."
    def raise_error(*args, **kwargs):
        raise socket.error
    def raise_herror(*args, **kwargs):
        raise socket.herror
    def raise_gaierror(*args, **kwargs):
        raise socket.gaierror
    self.failUnlessRaises(socket.error, raise_error,
    self.failUnlessRaises(socket.error, raise_herror,
    self.failUnlessRaises(socket.error, raise_gaierror,
        raise socket.error
    # Check that setting it to an invalid value raises ValueError
    # Check that setting it to an invalid type raises TypeError
    def raise_timeout(*args, **kwargs):
    self.failUnlessRaises(socket.timeout, raise_timeout,
    def raise_timeout(*args, **kwargs):
    self.failUnlessRaises(socket.timeout, raise_timeout,
</code></pre>
<p>Which is a pretty concise list of errors. Now of course this only works on a case by case basis and depends on the tests being accurate ( which they usually are ) . Otherwise you <span style="background-color:yellow;">need</span> to pretty much catch all exceptions , log them and dissect them and <span style="background-color:yellow;">figure</span> out how to handle them ( which with unit testing would <span style="background-color:yellow;">n't</span> be to difficult ) . </p>
<br /><b># 4 </b><br /><p><span style="background-color:yellow;">normally</span> , you 'd <span style="background-color:yellow;">need</span> to catch exception only around a <span style="background-color:yellow;">few</span> lines of code. You would <span style="background-color:yellow;">n't</span> want to put your whole main <span style="background-color:yellow;">function</span> into the try except clause. <span style="background-color:yellow;">for</span> every <span style="background-color:yellow;">few</span> line you always should <span style="background-color:yellow;">now</span> ( or be able easily to check ) what kind of exception might be raised . </p>
<p>docs have an exhaustive list of built-in exceptions . do <span style="background-color:yellow;">n't</span> try to except those exception that you 're <span style="background-color:yellow;">not</span> expecting , they might be handled/expected in the calling code . </p>
<p>edit : what might be thrown depends on obviously on what you 're doing ! accessing random element of a sequence : IndexError , random element of a dict : KeyError , etc . </p>
<p>Just try to run those <span style="background-color:yellow;">few</span> lines in IDLE and cause an exception. But unittest would be a better solution , <span style="background-color:yellow;">naturally</span> . </p>
<br /><b># 5 </b><br /><p>Noone explained so <span style="background-color:yellow;">far</span> , why you ca <span style="background-color:yellow;">n't</span> have a <span style="background-color:yellow;">full</span> , 100 % correct list of exceptions , so I thought it 's worth commenting on. One of the reasons is a <span style="background-color:yellow;">first-class</span> <span style="background-color:yellow;">function.</span> Let 's say that you have a <span style="background-color:yellow;">function</span> like this : </p>
<pre><code>def apl(f,arg):
   return f(arg)
</code></pre>
<p>Now <span style="background-color:yellow;">apl</span> can raise any exception that <span style="background-color:yellow;">f</span> raises. While there are <span style="background-color:yellow;">not</span> many <span style="background-color:yellow;">functions</span> like that in the core library , anything that uses list comprehension with custom <span style="background-color:yellow;">filters</span> , map , reduce , etc. are affected . </p>
<p>The documentation and the source analysers are the only " serious " sources of information here. Just keep in mind what they can <span style="background-color:yellow;">not</span> do . </p>
<br />